# Generated by Django 2.1 on 2018-09-11 13:21

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('text', models.TextField(max_length=30, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=300, null=True)),
                ('message', models.CharField(max_length=1000, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('turn', models.IntegerField(blank=True, null=True)),
                ('period_from', models.CharField(blank=True, choices=[('12.00 AM', '12.00 AM'), ('1.00 AM', '1.00 AM'), ('2.00 AM', '2.00 AM'), ('3.00 AM', '3.00 AM'), ('4.00 AM', '4.00 AM'), ('5.00 AM', '5.00 AM'), ('6.00 AM', '6.00 AM'), ('7.00 AM', '7.00 AM'), ('8.00 AM', '8.00 AM'), ('9.00 AM', '9.00 AM'), ('10.00 AM', '10.00 AM'), ('11.00 AM', '11.00 AM'), ('12.00 PM', '12.00 PM'), ('1.00 PM', '1.00 PM'), ('2.00 PM', '2.00 PM'), ('3.00 PM', '3.00 PM'), ('4.00 PM', '4.00 PM'), ('5.00 PM', '5.00 PM'), ('6.00 PM', '6.00 PM'), ('7.00 PM', '7.00 PM'), ('8.00 PM', '8.00 PM'), ('9.00 PM', '9.00 PM'), ('10.00 PM', '10.00 PM'), ('11.00 PM', '11.00 PM')], max_length=200, null=True)),
                ('period_to', models.CharField(blank=True, choices=[('12.00 AM', '12.00 AM'), ('1.00 AM', '1.00 AM'), ('2.00 AM', '2.00 AM'), ('3.00 AM', '3.00 AM'), ('4.00 AM', '4.00 AM'), ('5.00 AM', '5.00 AM'), ('6.00 AM', '6.00 AM'), ('7.00 AM', '7.00 AM'), ('8.00 AM', '8.00 AM'), ('9.00 AM', '9.00 AM'), ('10.00 AM', '10.00 AM'), ('11.00 AM', '11.00 AM'), ('12.00 PM', '12.00 PM'), ('1.00 PM', '1.00 PM'), ('2.00 PM', '2.00 PM'), ('3.00 PM', '3.00 PM'), ('4.00 PM', '4.00 PM'), ('5.00 PM', '5.00 PM'), ('6.00 PM', '6.00 PM'), ('7.00 PM', '7.00 PM'), ('8.00 PM', '8.00 PM'), ('9.00 PM', '9.00 PM'), ('10.00 PM', '10.00 PM'), ('11.00 PM', '11.00 PM')], max_length=200, null=True)),
                ('local_sold', models.CharField(blank=True, max_length=20, null=True)),
                ('amount_sold', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
